adeti_blog_user:
    resource: "@AdetiBlogBundle/Resources/config/routing.yml"
    prefix:   /

adeti_task:
    resource: "@AdetiBlogBundle/Resources/config/routing.php"
    prefix:   /

blog_:
    resource: "@AdetiBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
blog_index:
    path:      /
    defaults:  { _controller: AdetiBlogBundle:Article:liretout }
