blog_login_connexion:
    pattern:   /connexion
    defaults:  { _controller: AdetiBlogBundle:Security:login }

blog_login_tester_connexion:
    pattern:   /tester_connexion

blog_login_deconnexion:
    pattern:   /deconnexion

blog_login_admin:
    pattern:   /admin
    defaults: { _controller: AdetiBlogBundle:Blog:admin }

