
###discution###
#ajouter à la discussion
discuter_parler:
    path:     /parler
    defaults: { _controller: AdetiBlogBundle:Discuter:discuter }

#discussion:repondre a untel
discuter_repondreaquoi:
    path:     /repondre/ecrire
    defaults: { _controller: AdetiBlogBundle:Discuter:ecrire }
discuter_repondre:
    path:     /repondre/{a_ce_commentaire}
    defaults: { _controller: AdetiBlogBundle:Discuter:repondre }
discuter_voir:
    path:     /discuter
    defaults: { _controller: AdetiBlogBundle:Discuter:voirtous }
