#####################################################
###contact###
#nous ecrire (animateurs):
adeti_blog_discuter:
    path:     /nous-ecrire
    defaults: { _controller: AdetiCaptchaBundle:Blog:accueil }
#ecrire aux admin(mailing list CA/bureau)
adeti_blog_discuter:
    path:     /le-CA
    defaults: { _controller: AdetiCaptchaBundle:Default:index }

#ecrire a la list
adeti_blog_discuter:
    path:     /tout-le-monde
    defaults: { _controller: AdetiCaptchaBundle:Default:index }
