#article controler et discutez controler
###article et commentaires dessus###
#article:
blog_article_publier:
    path:     /publier
    defaults: { _controller: AdetiBlogBundle:Article:publier }


#=blogindex! voir articles
blog_article_liretout:
    path:     /lire-tous
    defaults: { _controller: AdetiBlogBundle:Article:liretout }

#voir 1  article=commentez,repondre...
blog_article_lire:
    path:     /lire/{article}
    defaults: { _controller: AdetiBlogBundle:Article:lire }
    requirements:
        article:  \d*
