_welcome:
    pattern:  /
    defaults: { _controller: @AcmeDemoBundle:Welcome:index }

_welcomeb:
    pattern:  /lug/
    defaults: { _controller: @AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
_blog:
    resource: "@AdetiBlogBundle/BlogManager.php"
    type:     annotation
    prefix:   /blog

_contact:
    resource: "@AdetiBlogBundle/MailManager.php"
    type:     annotation
    prefix:   /contact

_contact:
    resource: "@AdetiCaptchaBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /cont
