
adeti_blog_formtest:
    path:     /formtest
    defaults: { _controller: AdetiBlogBundle:Blog:formtest }
adeti_blog_menu:
    path:     /menu
    defaults: { _controller: AdetiBlogBundle:Blog:menu }
sdzblog_voir_slug:
    path:      /blog/{annee}/{slug}.{format}
    defaults:  { _controller: SdzBlogBundle:Blog:voirSlug, format: html }
    requirements:
        annee:  \d{4}
        format: html|xml
article_:
    resource: routingarticle.yml
    prefix:   /article

_discuter:
    resource: routingdiscuter.yml
    prefix:   /discuter
_contact:
    resource: routingcontact.yml
    prefix:   /contact

_login:
    resource: routinglogin.yml
    prefix:   /login


