parameters:
#    adeti_captcha.example.class: Adeti\CaptchaBundle\Example

services:
#    adeti_captcha.example:
#        class: %adeti_captcha.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
