parameters:
#    adeti_blog.example.class: Adeti\BlogBundle\Example

services:
#    adeti_blog.example:
#        class: %adeti_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
